### ISSUE TITLE
fix writing to user_record.py - make it a dinner log with date

### ISSUE THREAD

**Issue by h3nd3r** [h3nd3r/nutrition_pro#20]

**Comment by itasari** [comment]
@h3nd3r: thoughts on how to make it so that it doesn't ask "what have you eaten in the past several days" when it's already in the user_record?

<img width="832" alt="Screenshot 2024-10-10 at 9 19 21 PM" src="https://github.com/user-attachments/assets/22462412-a320-47b9-900f-67e81bde9678">

**Comment by itasari** [comment]
some ideas on modifications:
* Take out Client Information
* Alerts: make it more specific to just track when user's not meeting nutrition goals with their dinner (instead of the whole blurb we have in there currently)
* Meal Preferences: I'm tempted to just axe this since we are not using it for RAG
* Chat Records: replace this with Dinner Logs

**Comment by h3nd3r** [comment]
I removed the alerts.  We need to rag this or get the recorder LLM to pass this info back.  Let's discuss today, I see you created a ticket to address.

**Comment by h3nd3r** [comment]
https://github.com/h3nd3r/nutrition_pro/commit/681d04c5f7bb0b3001965d6284988ab21cf8d5a1
